### ISSUE TITLE
Use official English course names

### ISSUE THREAD

**Issue by hadisfr** [AMK6610/CourseDescription#5]
It may be a good idea to use official English names as in English transcript (e.g. "Automata and Language Theory"), CECM (e.g. ["The Theory of Formal Languages and Automata"](https://cecm.ut.ac.ir/enrol/index.php?id=2520) or ["Formal Languages and Automata Theory"](https://cecm.ut.ac.ir/enrol/index.php?id=2812)) or [ABET](https://ece.ut.ac.ir/abet) (e.g. "Automata and Language Theory" ) instead of unofficial translated names (e.g. ["Machines and Language Theory"](https://github.com/AMK6610/CourseDescription#machines-and-language-theory)).

**Comment by AMK6610** [comment]
All names are derived from the official transcript the university provides. You're right but I guess it's better this way because there will be one unique name for each course in the transcript and the course description file.
